DROP FUNCTION IF EXISTS makeupper;
 
DELIMITER $$
CREATE FUNCTION makeupper(str_value VARCHAR(5000))
RETURNS VARCHAR(5000)
DETERMINISTIC
BEGIN
    RETURN CONCAT(UCASE(LEFT(str_value, 1)),SUBSTRING(str_value, 2));
END
$$